# Generated by Django 3.1 on 2020-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
