# Generated by Django 3.1 on 2020-09-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination1',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enroll.destination')),
                ('star', models.CharField(max_length=23)),
                ('all', models.CharField(max_length=43)),
                ('ticket', models.CharField(max_length=45)),
                ('visits', models.CharField(max_length=20)),
            ],
            bases=('enroll.destination',),
        ),
    ]
