# Generated by Django 3.1.1 on 2020-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_destination1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=45)),
                ('subject', models.CharField(max_length=34)),
                ('message', models.CharField(max_length=343)),
            ],
        ),
    ]
