# Generated by Django 3.1.1 on 2020-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besttrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=23)),
                ('descrip', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='destination',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
