# Generated by Django 3.1.1 on 2020-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20200919_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('descrip', models.CharField(max_length=80)),
            ],
        ),
    ]
