# Generated by Django 3.1.1 on 2020-09-20 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_newstrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=34),
            preserve_default=False,
        ),
    ]
