# Generated by Django 3.1.1 on 2020-09-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_subscribe_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=34)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=56)),
                ('message', models.CharField(max_length=67)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='subject',
        ),
    ]
